### ISSUE TITLE
Tracker doesn't register tags nested under blocks

### ISSUE THREAD

**Issue by bezark** [hkgnp/logseq-trackhabits2-plugin#1]
Great plugin! Really excited to start using it!

One thing I noticed: I think the tracker won't render blocks that are nested. for instance:
- Habits
	- TODO readwise #habit-tracker

Seems to break the renderer.

**Comment by benjypng** [comment]
Hey! Thanks for the feedback!
Fixed in release v1.1!
Can update from the marketplace.

**Comment by bezark** [comment]
Nice! Thanks!
-John (he/they)
____________
Portfolio <http://www.johnbezark.info> | Blog <https://www.johnbezark.com>
